### ISSUE TITLE
Google Maps API as Geocoding Service in ArcGIS Server

### ISSUE THREAD

**Issue by kphaneuf** [vta/GIS_Projects#14]
Figure out how we can use the Google API to create a geocoding service in ArcGIS Server to then be used in Geocortex and ArcMap.

**Comment by kphaneuf** [comment]
Need to figure out how to create our own Google API module for Geocortex similar to the one they created for Bing.  This is located on ROVGIS02
C:\Program Files (x86)\Latitude Geographics\Geocortex Essentials\Default\REST Elements\Manager\Views\GeocodingEndpointWizard

**Comment by 3vivekb** [comment]
Integrating the Google Api module seems like it would be a ton of work.

The stuff we wanted to accomplish was mainly to constrain searches to just Santa Clara County, which we could do with just reconfiguring the current Geocortex geo-coder with a search boundary.  Which we did.
